{
 "title": "sensor-exporter",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "vibration",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "vibration_level", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "temperature_celsius",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "temperature_celsius", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "humidity",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "humidity_percentage", "legendFormat": "__auto" }
   ]
  }
 ]
}